spring.application.name=Library-management-System
server.port=8080

# Logging
logging.level.com.krish=DEBUG
logging.level.org.springframework.web=DEBUG

# Database - PostgreSQL (Neon)
spring.datasource.url=jdbc:postgresql://ep-dry-hill-aducis6m-pooler.c-2.us-east-1.aws.neon.tech/library_db?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_sAUMVZgD02YR
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# JWT Configuration
jwt.secret.key=ejvdqyfqiyveyvqeyevfkyevfkyevfkyevfkvkevkqvkqv

# Mail - Use Gmail App Password
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=loharkrish95@gmail.com
spring.mail.password=@Rezero9095
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.test-connection=false

# Razorpay
razorpay.key.id=rzp_test_SRCCxBFAK0gQZ0
razorpay.key.secret=z1EUJy2RjQIzk1sBW8BD8OpF
razorpay.callback.base-url=http://localhost:5173

# Admin User Configuration
admin.email=loharkrish95@gmail.com
admin.password=@Rezero9095
